### ISSUE TITLE
"type" property of VerifiableID for Natural Person already defined

### ISSUE THREAD

**Issue by alejandro-nieto-git** [smart-data-models/dataModel.VerifiableCredentials#1]
The "type" property of VerifiableID for Natural Person is already defined in the Verifiable Attestation. This is the schema that I'm talking about: https://github.com/smart-data-models/dataModel.VerifiableCredentials/blob/master/NaturalPerson/schema.json

**Comment by albertoabellagarcia** [comment]
Not clear to me, because in the only $ref in the schema points to https://raw.githubusercontent.com/smart-data-models/dataModel.VerifiableCredentials/master/VerifiableCredentials-schema.json  and it does not define first level property 'type'.
What am I missing?

**Comment by alejandro-nieto-git** [comment]
You are correct. I though that link was https://github.com/smart-data-models/dataModel.VerifiableCredentials/blob/master/Attestation/schema.json instead. In this case why did you create a specific VerifiableCredentials-schema.json without a "type" property when all the credentials need that field? Am I missing something else maybe?

**Comment by alejandro-nieto-git** [comment]
Another question is why did you create a schema for VerifiableCredentials when the VerifiableAttestation is like the minimal Credential allowed, I mean conceptually those two are the same thing.

**Comment by albertoabellagarcia** [comment]
VerifiableCredentials-schema.json is just a shared file for being embedded into the different data models. It is not an entity by itself because it does not have a type (of entity). But certainly, it is, but for this, very close if not identical.
