### ISSUE TITLE
Redundant required "credentialSubject" in the Verifiable ID for Natural Persons

### ISSUE THREAD

**Issue by alejandro-nieto-git** [smart-data-models/dataModel.VerifiableCredentials#2]
The "credentialSubject" property of VerifiableID for Natural Person is already defined as required in the Verifiable Attestation. This is the schema that I'm talking about: https://github.com/smart-data-models/dataModel.VerifiableCredentials/blob/master/NaturalPerson/schema.json

**Comment by albertoabellagarcia** [comment]
I agree that verifiableattestation includes as required the credentialsubject. And it is true that the original EBSI schema embeds the verifiableattestation, where the credentialsubject is required. Do you mean that we should also add as required the credentialsubject in the natural person?

**Comment by alejandro-nieto-git** [comment]
I meant that in the VID for Natural Persons the credentialSubject is set as required too although in the VA schema it is already set as required so I think it is redundant.

**Comment by albertoabellagarcia** [comment]
Yes, it is redundant when used together but eventually, they could be used individually. This was the case, then it would not be redundant
